a = int(input("Enter your Age : "))
print("Your age is : ",a)
print(a>18)
print(a>=18)
print(a<18)
print(a<=18)
if( a >= 18 ) : print("You can Drive")
elif(a>70) : print("You are too Old Sir") 
else : print("You cannot Drive")